import { GalleryItem } from '../types';

export const GALLERY_DATA: GalleryItem[] = [
  {
    id: 'lookbook-1',
    title: 'Mid Zero Skin Fade & Textured Top',
    category: 'fades',
    categoryLabel: 'Skin Fade',
    imageUrl: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=1200&q=85',
    beforeImageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=1200&q=85',
    description: 'Precision mid-zero shaver fade with texturized crown weight and crisp razor-edging.',
    aspectRatio: 'portrait',
  },
  {
    id: 'lookbook-2',
    title: 'Executive Low Taper & Side Part',
    category: 'executive',
    categoryLabel: 'Executive Cut',
    imageUrl: 'https://images.unsplash.com/photo-1599351431202-1e0f0137899a?auto=format&fit=crop&w=1200&q=85',
    description: 'Tailored scissor-over-comb side parting with soft neck taper for modern corporate style.',
    aspectRatio: 'square',
  },
  {
    id: 'lookbook-3',
    title: 'Architectural Beard Sculpt & Razor Line',
    category: 'beards',
    categoryLabel: 'Beard Sculpting',
    imageUrl: 'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?auto=format&fit=crop&w=1200&q=85',
    beforeImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1200&q=85',
    description: 'Bespoke cheek-line razor sculpt, foil mustache reduction, and hot organic oil finish.',
    aspectRatio: 'portrait',
  },
  {
    id: 'lookbook-4',
    title: 'Royal Hot Towel Steam Treatment',
    category: 'hot-towel',
    categoryLabel: 'Hot Towel Spa',
    imageUrl: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&w=1200&q=85',
    description: 'Dual steam towel preparation, badger brush lathering, and cut-throat razor shave.',
    aspectRatio: 'landscape',
  },
  {
    id: 'lookbook-5',
    title: 'High Razor Fade & Crop Top',
    category: 'fades',
    categoryLabel: 'Skin Fade',
    imageUrl: 'https://images.unsplash.com/photo-1605497788044-5a32c7078486?auto=format&fit=crop&w=1200&q=85',
    description: 'Sharp high razor skin fade paired with messy textured French crop fringe.',
    aspectRatio: 'square',
  },
  {
    id: 'lookbook-6',
    title: 'VIP Private Suite Full Transformation',
    category: 'vip',
    categoryLabel: 'VIP Suite',
    imageUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=1200&q=85',
    beforeImageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=85',
    description: 'Complete 90-minute VIP treatment: haircut, beard sculpting, facial steam, and scotch tasting.',
    aspectRatio: 'portrait',
  },
];
