import { GroomingService } from '../types';

export const SERVICES_DATA: GroomingService[] = [
  {
    id: 'exec-cut',
    name: 'The Executive Haircut',
    category: 'haircuts',
    durationMinutes: 45,
    priceGBP: 38,
    description: 'Precision consult, tailored haircut, hair wash, hot towel neck clean-up, and luxury style finish.',
    inclusions: ['Personal Consultation', 'Precision Scissors/Clipper Work', 'Scalp Refresh Wash', 'Hot Towel Finish'],
    isPopular: true,
  },
  {
    id: 'skin-fade',
    name: 'Signature Precision Skin Fade',
    category: 'haircuts',
    durationMinutes: 50,
    priceGBP: 42,
    description: 'Seamless razor-sharp skin fade tailored to your skull shape with foil shaver refinement and styling.',
    inclusions: ['Skull Shape Analysis', 'Foil Shaver Zero Fade', 'Texturizing & Styling', 'Complimentary Beverage'],
    isPopular: true,
  },
  {
    id: 'beard-sculpt',
    name: 'Bespoke Beard Sculpt & Line-Up',
    category: 'beards',
    durationMinutes: 30,
    priceGBP: 26,
    description: 'Beard trimming, foil edging, open-razor cheek line, and nourishing hot organic oil massage.',
    inclusions: ['Length Reduction & Shape', 'Cut-Throat Razor Line', 'Hot Towel Steam Treatment', 'Beard Conditioning Oil'],
  },
  {
    id: 'hot-towel-shave',
    name: 'Traditional Royal Hot-Towel Shave',
    category: 'beards',
    durationMinutes: 45,
    priceGBP: 35,
    description: 'Multi-stage hot towel preparation, badger brush lathering, straight razor shave, and cold towel pore closure.',
    inclusions: ['Pre-Shave Oil Massage', 'Dual Hot Towels', 'Single-Blade Cut-Throat Shave', 'Cold Towel & Aftershave Balm'],
  },
  {
    id: 'the-boss-combo',
    name: 'The BOSS Full Grooming Experience',
    category: 'combos',
    durationMinutes: 75,
    priceGBP: 65,
    description: 'Our signature package combining The Executive Haircut with Bespoke Beard Sculpt & Hot Towel Finish.',
    inclusions: ['Executive Haircut', 'Beard Sculpting or Cut-Throat Shave', 'Scalp Wash', 'Complimentary Single-Malt Whisky'],
    isPopular: true,
  },
  {
    id: 'vip-lounge',
    name: 'VIP Private Suite Session',
    category: 'vip',
    durationMinutes: 90,
    priceGBP: 95,
    description: 'Exclusive access to our private VIP styling bay, complete hair & beard treatment, facial steam, and premium drink selection.',
    inclusions: ['Private Suite Reservation', 'Full Hair & Beard Treatment', 'Facial Steam & Scrub', 'Premium Spirits Bar Access'],
  },
];
